CREATE TABLE IF NOT EXISTS resources (
    id INTEGER PRIMARY KEY,
    user_id INTEGER DEFAULT 1,
    path TEXT UNIQUE NOT NULL,
    content TEXT,
    size INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_path ON resources(path);
